spring:
  banner:
    location: classpath:banner.txt
  datasource:
      url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:15432/midterm}
      username: ${SPRING_DATASOURCE_USERNAME:midterm}
      password: ${SPRING_DATASOURCE_PASSWORD:password}
      driver-class-name: org.postgresql.Driver
  liquibase:
      change-log: classpath:db/changelog/db.changelog-master.xml

game:
  deck:
    zero: 1
    number: 2
    skip: 2
    reverse: 2
    draw-two: 2
    wild: 4
    wild-draw-four: 4
    player-cards: 7